version: '3'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: realestatedb
      MYSQL_ROOT_PASSWORD: root
    command: ["--default-authentication-plugin=mysql_native_password"]

    volumes:
      - ./:/docker-entrypoint-initdb.d
    networks:
      - api-network

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mi-api
    environment:
      DB_PORT: 3306
      APP_PORT: 3000
      DB_HOST: db
      DB_USER: admin
      DB_PASS: admin
      MYSQL_DB: realestatedb
      KEY_JWT: 50?G£7vgFv<y<1je:5)nH4^&Ug|4(I!{@24)
    ports:
      - "8080:3000"
    depends_on:
      - db
    networks:
      - api-network

volumes:
  mysql-data:

networks:
  api-network:
    driver: bridge

    